# Generated by Django 2.2.2 on 2019-07-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
